'use client';

import { useState } from 'react';
import type { Certificate } from '@/types/database';
import { Button } from '@/components/ui/button';
import {
  X, Download, RefreshCw, Send, ShieldCheck, ExternalLink,
  Award, CheckCircle2, AlertCircle, Clock, FileCheck,
} from 'lucide-react';

// ─── Status badge ─────────────────────────────────────────────────────────────

const STATUS_META: Record<string, { label: string; cls: string; Icon: React.ComponentType<{ className?: string }> }> = {
  pending:    { label: 'Pending',    cls: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',     Icon: Clock },
  generated:  { label: 'Generated',  cls: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',             Icon: FileCheck },
  downloaded: { label: 'Downloaded', cls: 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400',     Icon: Download },
  verified:   { label: 'Verified',   cls: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400', Icon: CheckCircle2 },
  failed:     { label: 'Failed',     cls: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',                 Icon: AlertCircle },
};

function StatusBadge({ status }: { status: string }) {
  const meta = STATUS_META[status] ?? { label: status, cls: 'bg-muted text-muted-foreground', Icon: Award };
  const { label, cls, Icon } = meta;
  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium ${cls}`}>
      <Icon className="h-2.5 w-2.5" />
      {label}
    </span>
  );
}

// ─── Props ────────────────────────────────────────────────────────────────────

export type PreviewAction = 'download' | 'regenerate' | 'resend' | 'verify';

interface CertificatePreviewModalProps {
  cert: Certificate;
  onClose: () => void;
  /** Called with the action ID when staff clicks an action inside the modal */
  onAction?: (action: PreviewAction) => Promise<void>;
}

// ─── Preview frame ────────────────────────────────────────────────────────────

function PreviewFrame({ cert }: { cert: Certificate }) {
  const [imgError, setImgError] = useState(false);

  // 1. If there's a preview thumbnail — show it
  if (cert.preview_url && !imgError) {
    return (
      <div className="relative w-full rounded-lg overflow-hidden border bg-muted flex items-center justify-center" style={{ minHeight: 320 }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={cert.preview_url}
          alt={`Preview of certificate ${cert.certificate_number ?? cert.id}`}
          className="max-w-full max-h-[480px] object-contain"
          onError={() => setImgError(true)}
        />
        {/* Overlay: open in new tab */}
        {cert.download_url && (
          <a
            href={cert.download_url}
            target="_blank"
            rel="noopener noreferrer"
            className="absolute bottom-3 right-3 flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-black/60 text-white text-xs font-medium hover:bg-black/80 transition-colors"
          >
            <ExternalLink className="h-3 w-3" />
            Open PDF
          </a>
        )}
      </div>
    );
  }

  // 2. If there's a download URL but no preview — show an iframe for the PDF
  if (cert.download_url) {
    return (
      <div className="relative w-full rounded-lg overflow-hidden border bg-muted" style={{ minHeight: 400 }}>
        <iframe
          src={cert.download_url}
          title={`Certificate ${cert.certificate_number ?? cert.id}`}
          className="w-full"
          style={{ height: 440 }}
        />
      </div>
    );
  }

  // 3. No preview available yet
  return (
    <div
      className="w-full rounded-lg border bg-muted/40 flex flex-col items-center justify-center gap-3 text-muted-foreground"
      style={{ minHeight: 280 }}
      role="img"
      aria-label="Certificate preview unavailable"
    >
      <Award className="h-12 w-12 opacity-30" />
      <div className="text-center space-y-1">
        <p className="text-sm font-medium">Preview unavailable</p>
        <p className="text-xs">
          {cert.status === 'pending'
            ? 'Certificate is being generated by the backend engine.'
            : cert.status === 'failed'
            ? 'Certificate generation failed. Use Regenerate to retry.'
            : 'No preview URL returned by the certificate engine.'}
        </p>
      </div>
    </div>
  );
}

// ─── Modal ────────────────────────────────────────────────────────────────────

export function CertificatePreviewModal({ cert, onClose, onAction }: CertificatePreviewModalProps) {
  const [actionLoading, setActionLoading] = useState<PreviewAction | null>(null);

  async function handle(action: PreviewAction) {
    if (!onAction) return;
    setActionLoading(action);
    try {
      await onAction(action);
    } finally {
      setActionLoading(null);
    }
  }

  const busy = (a: PreviewAction) => actionLoading === a;

  const canDownload   = !!cert.download_url;
  const canRegenerate = ['failed', 'generated', 'downloaded'].includes(cert.status);
  const canVerify     = cert.status !== 'verified';

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 z-50 bg-black/50 backdrop-blur-[2px]"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Modal panel */}
      <div
        className="fixed inset-0 z-50 flex items-center justify-center p-4"
        role="dialog"
        aria-modal="true"
        aria-label={`Certificate preview: ${cert.certificate_number ?? cert.id}`}
      >
        <div
          className="relative bg-background rounded-xl shadow-2xl border w-full max-w-2xl flex flex-col max-h-[90vh] overflow-hidden"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex items-start justify-between px-5 py-4 border-b shrink-0 gap-4">
            <div className="flex items-start gap-3 min-w-0">
              <div className="p-2 rounded-lg bg-primary/10 shrink-0">
                <Award className="h-5 w-5 text-primary" />
              </div>
              <div className="min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <h2 className="font-bold text-base truncate">
                    {cert.certificate_number || cert.id.slice(0, 12) + '…'}
                  </h2>
                  <StatusBadge status={cert.status} />
                </div>
                <p className="text-xs text-muted-foreground mt-0.5">
                  {cert.certificate_type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}
                  {cert.amount != null && ` · ₹${cert.amount.toLocaleString('en-IN')}`}
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 rounded-md hover:bg-muted transition-colors shrink-0"
              aria-label="Close preview"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Certificate preview frame */}
          <div className="flex-1 overflow-y-auto p-5 space-y-4">
            <PreviewFrame cert={cert} />

            {/* Meta grid */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-sm">
              <div>
                <p className="text-xs text-muted-foreground mb-0.5">Trader</p>
                <p className="font-mono text-xs truncate">{cert.user_id.slice(0, 16)}…</p>
              </div>
              {cert.payout_id && (
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Payout</p>
                  <p className="font-mono text-xs truncate">{cert.payout_id.slice(0, 16)}…</p>
                </div>
              )}
              {cert.generated_at && (
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Generated</p>
                  <p className="text-xs">{new Date(cert.generated_at).toLocaleDateString()}</p>
                </div>
              )}
              {cert.verification_url && (
                <div className="col-span-full">
                  <p className="text-xs text-muted-foreground mb-0.5">Verification Link</p>
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs text-muted-foreground truncate flex-1">
                      {cert.verification_url.slice(0, 55)}…
                    </span>
                    <a
                      href={cert.verification_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="shrink-0 flex items-center gap-1 text-xs text-primary hover:underline"
                    >
                      <ExternalLink className="h-3 w-3" />
                      Open
                    </a>
                  </div>
                </div>
              )}
            </div>

            {/* Failure reason */}
            {cert.failure_reason && (
              <div className="flex items-start gap-2 text-xs text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 rounded-lg px-3 py-2">
                <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
                <span>{cert.failure_reason}</span>
              </div>
            )}
          </div>

          {/* Action footer */}
          <div className="px-5 py-4 border-t bg-muted/30 flex flex-wrap items-center gap-2 shrink-0">
            {canDownload && (
              <Button
                size="sm"
                className="gap-1.5"
                onClick={() => handle('download')}
                disabled={!!actionLoading}
              >
                {busy('download')
                  ? <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                  : <Download className="h-3.5 w-3.5" />}
                Download
              </Button>
            )}

            {canRegenerate && (
              <Button
                variant="outline"
                size="sm"
                className="gap-1.5"
                onClick={() => handle('regenerate')}
                disabled={!!actionLoading}
              >
                {busy('regenerate')
                  ? <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                  : <RefreshCw className="h-3.5 w-3.5" />}
                Regenerate
              </Button>
            )}

            <Button
              variant="outline"
              size="sm"
              className="gap-1.5"
              onClick={() => handle('resend')}
              disabled={!!actionLoading}
            >
              {busy('resend')
                ? <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                : <Send className="h-3.5 w-3.5" />}
              Resend Email
            </Button>

            {canVerify && (
              <Button
                variant="outline"
                size="sm"
                className="gap-1.5"
                onClick={() => handle('verify')}
                disabled={!!actionLoading}
              >
                {busy('verify')
                  ? <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                  : <ShieldCheck className="h-3.5 w-3.5" />}
                Verify
              </Button>
            )}

            <div className="ml-auto">
              <Button variant="ghost" size="sm" onClick={onClose}>
                Close
              </Button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
