FROM node:22-slim

WORKDIR /app

RUN npm install --global pnpm@11.8.0

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @workspace/api-server run build

CMD ["node", "--enable-source-maps", "./artifacts/api-server/dist/index.mjs"]
