#!/usr/bin/env node
/*
 * Simple invite code generator.
 * Usage: `node scripts/generate_invite_codes.js 100 out/invite_codes.csv`
 * Produces CSV with columns: code,assigned_email,created_at,notes
 * The script intentionally only generates a CSV for manual ingestion to avoid
 * coupling to application schema or secrets during Phase 12 operations.
 */
import fs from "fs";
import path from "path";

function randChunk(len = 4) {
  const chars = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"; // avoid ambiguous chars
  let s = "";
  for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

function generateCode() {
  return `${randChunk(4)}-${randChunk(4)}-${randChunk(4)}`;
}

const args = process.argv.slice(2);
const count = Number(args[0] || 10);
const out = args[1] || "out/invite_codes.csv";

if (!Number.isFinite(count) || count <= 0) {
  console.error("Invalid count");
  process.exit(2);
}

const rows: string[] = [];
rows.push("code,assigned_email,created_at,notes");
for (let i = 0; i < count; i++) {
  const code = generateCode();
  const created = new Date().toISOString();
  rows.push(`${code},,${created},"generated by scripts/generate_invite_codes.ts"`);
}

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, rows.join("\n"), { encoding: "utf8" });
console.log(`Wrote ${count} invite codes to ${out}`);
